/**
 * Structured representation of the FBDL language — every setup entity and action,
 * their parameters, types, and constraints. Derived from Meta's FBDL docs.
 */

export interface Param {
  readonly name: string;
  readonly required: boolean;
  readonly description: string;
  readonly values?: readonly string[];
  readonly isList?: boolean;
}

export interface SetupEntity {
  readonly type: string;
  readonly description: string;
  readonly hasLabel: boolean;
  readonly params: readonly Param[];
  readonly example: string;
}

export interface Action {
  readonly name: string;
  readonly description: string;
  readonly signature: string;
  readonly supportsVoiceSwitcher: boolean;
  readonly targetTypes: readonly string[];
  readonly positionalParams: readonly Param[];
  readonly keywordParams: readonly Param[];
  readonly examples: readonly string[];
}

// ── Setup Entities ──────────────────────────────────────────────────────────

export const SETUP_ENTITIES: readonly SetupEntity[] = [
  {
    type: "User",
    description: "Create a Whitehat test user.",
    hasLabel: true,
    params: [],
    example: "[setup] User UserOne",
  },
  {
    type: "Page",
    description: "Create a Page with various setting options.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "The owner of the page" },
      {
        name: "is_parent_location",
        required: false,
        description: "Mark as parent location page.",
        values: ["false", "true"],
      },
      {
        name: "admins",
        required: false,
        description: "Users to add as page admins.",
        isList: true,
      },
      {
        name: "editors",
        required: false,
        description: "Users to add as page editors.",
        isList: true,
      },
      {
        name: "moderators",
        required: false,
        description: "Users to add as page moderators.",
        isList: true,
      },
      {
        name: "advertisers",
        required: false,
        description: "Users to add as page advertisers.",
        isList: true,
      },
      {
        name: "analysts",
        required: false,
        description: "Users to add as page analysts.",
        isList: true,
      },
    ],
    example: "[setup] User UserOne Page PageOne with {owner: UserOne}",
  },
  {
    type: "Group",
    description: "Create a Group with various setting options.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "Owner of the group." },
      {
        name: "privacy",
        required: true,
        description: "Privacy setting.",
        values: ["public", "private", "public_legacy"],
      },
      {
        name: "visibility",
        required: false,
        description: "Visibility setting.",
        values: ["anyone", "members_only"],
      },
      { name: "members", required: false, description: "List of members.", isList: true },
      { name: "admins", required: false, description: "List of admins.", isList: true },
      { name: "moderators", required: false, description: "List of moderators.", isList: true },
      { name: "name", required: false, description: "Name of the group." },
      { name: "description", required: false, description: "Description of the group." },
      {
        name: "allow_anonymous_posts",
        required: false,
        description: "Allow anonymous posts.",
        values: ["false", "true"],
      },
      {
        name: "pending_participants",
        required: false,
        description: "Pending participants for public community.",
        isList: true,
      },
      {
        name: "approved_participants",
        required: false,
        description: "Approved participants for public community.",
        isList: true,
      },
      {
        name: "participation_control_enabled",
        required: false,
        description: "Toggle participation controls for Public Communities.",
        values: ["false", "true"],
      },
    ],
    example:
      "[setup] User MemberOne User MemberTwo User OwnerOne User AdminOne Group GroupOne with {owner: OwnerOne, privacy: private, members:[MemberOne, MemberTwo], admins: [AdminOne]}",
  },
  {
    type: "Album",
    description: "Create a photo Album with various setting options.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "The owner of the album." },
      {
        name: "type",
        required: true,
        description: "The type of the album.",
        values: ["user", "shared", "page", "group"],
      },
      { name: "place", required: true, description: "Where the album is from (User/Page/Group)." },
      {
        name: "privacy",
        required: false,
        description: "Privacy setting of the album.",
        values: [
          "public",
          "friends_only",
          "only_me",
          "contributors_only",
          "friends_of_contributors",
        ],
      },
      {
        name: "contributors",
        required: false,
        description: "List of contributors for shared albums.",
        isList: true,
      },
      {
        name: "actor",
        required: false,
        description: "Page to create the album as (for group albums).",
      },
    ],
    example:
      "[setup] User UserOne Album AlbumOne with {owner: UserOne, type: user, place: UserOne, privacy: friends_only}",
  },
  {
    type: "Friendship",
    description: "Create friendship between Users.",
    hasLabel: false,
    params: [
      { name: "sender", required: true, description: "The sender of the friend request." },
      {
        name: "receivers",
        required: true,
        description: "List of receivers.",
        isList: true,
      },
    ],
    example:
      "[setup] User UserOne User UserTwo Friendship with {sender: UserOne, receivers: [UserTwo]}",
  },
  {
    type: "Business",
    description: "Create a Business with various setting options.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "The owner of the business." },
      { name: "admins", required: false, description: "List of admins.", isList: true },
      { name: "employees", required: false, description: "List of employees.", isList: true },
      { name: "primary_page", required: false, description: "The primary page the business owns." },
      {
        name: "tier",
        required: false,
        description: "Trust tier.",
        values: ["tier_0", "tier_1", "tier_2", "tier_3"],
      },
      {
        name: "quarantine",
        required: false,
        description: "Sets business under quarantine.",
        values: ["false", "true"],
      },
    ],
    example: "[setup] User OwnerOne Business BizOne with {owner: OwnerOne, quarantine: true}",
  },
  {
    type: "App",
    description: "Create an App with owner and live status.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "The owner of the app." },
      {
        name: "live",
        required: false,
        description: "Whether the app is published.",
        values: ["true", "false"],
      },
      {
        name: "type",
        required: false,
        description: "The app type.",
        values: ["business", "workplace", "consumer", "instant_games", "gaming", "none"],
      },
    ],
    example:
      "[setup] User OwnerOne App AppOne with {owner: OwnerOne, live: false, type: instant_games}",
  },
  {
    type: "Event",
    description: "Create an event with various setting options.",
    hasLabel: true,
    params: [
      { name: "owner", required: true, description: "The owner of the event." },
      { name: "place", required: true, description: "Where the event is (user/page/group label)." },
      {
        name: "privacy",
        required: false,
        description: "Privacy for user-placed events.",
        values: ["public", "private"],
      },
      {
        name: "is_past",
        required: false,
        description: "Whether event is in the past.",
        values: ["false", "true"],
      },
      {
        name: "post_permission",
        required: false,
        description: "Who can post.",
        values: ["admin", "anyone"],
      },
      {
        name: "post_approval",
        required: false,
        description: "Post approval setting.",
        values: ["on", "off"],
      },
      {
        name: "accept_invite",
        required: false,
        description: "Auto-accept co-host invites.",
        values: ["false", "true"],
      },
      {
        name: "show_guest_list",
        required: false,
        description: "Show guest list.",
        values: ["false", "true"],
      },
      { name: "co_hosts", required: false, description: "List of co-hosts.", isList: true },
    ],
    example:
      "[setup] User OwnerOne User MemberOne Group GroupOne with {owner: OwnerOne, members:[MemberOne]} Event EventOne with {owner: OwnerOne, place: GroupOne, post_permission:anyone, post_approval:on}",
  },
] as const;

// ── Actions ─────────────────────────────────────────────────────────────────

export const ACTIONS: readonly Action[] = [
  {
    name: "make_anonymous_post",
    description: "Make an anonymous post in a health or parenting type group.",
    signature: "Subject as Subject make_anonymous_post Label with {group, approved_by}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Label for the post." }],
    keywordParams: [
      { name: "group", required: true, description: "Group to post in." },
      { name: "approved_by", required: true, description: "User who approves the post." },
    ],
    examples: [
      "UserTwo make_anonymous_post AnonPostOne with {group:GroupOne, approved_by: UserOne}",
    ],
  },
  {
    name: "make_post_text",
    description: "Make a text post as User or Page. Voice switcher supported.",
    signature: "Subject as Subject make_post_text Label with {place, ?text, ?tagged_object}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the post." }],
    keywordParams: [
      { name: "place", required: true, description: "Where to post (User/Page/Event/Group)." },
      { name: "text", required: false, description: "Text message. Default is random." },
      { name: "tagged_object", required: false, description: "Object to tag (User/Page)." },
    ],
    examples: [
      "UserOne as PageOne make_post_text PostOne with {place: GroupOne, text: 'This is my first group post as Page'}",
      "UserOne make_post_text PostOne with {place: UserOne}",
    ],
  },
  {
    name: "make_post_photo",
    description: "Make a photo post as User or Page. Voice switcher supported.",
    signature: "Subject as Subject make_post_photo Label with {place, ?text, ?tagged_object}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the post." }],
    keywordParams: [
      { name: "place", required: true, description: "Where to post (User/Page/Event/Group)." },
      { name: "text", required: false, description: "Text message. Default is random." },
      { name: "attachment_label", required: false, description: "Label for the photo attachment." },
      {
        name: "multiple_photos",
        required: false,
        description: "Multiple photos needed.",
        values: ["false", "true"],
      },
      { name: "tagged_object", required: false, description: "Object to tag (User/Page)." },
    ],
    examples: [
      "UserOne as PageOne make_post_photo PostOne with {place: GroupOne, text: 'This is my first group post as Page', attachment_label: PhotoOne}",
      "UserOne make_post_photo PostOne with {place: UserOne, attachment_label: PhotoOne}",
    ],
  },
  {
    name: "make_post_video",
    description: "Make a video post as User or Page. Voice switcher supported.",
    signature:
      "Subject as Subject make_post_video Label with {place, ?text, ?attachment_label, ?tagged_object}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the post." }],
    keywordParams: [
      { name: "place", required: true, description: "Where to post (User/Page/Event/Group)." },
      { name: "text", required: false, description: "Text message. Default is random." },
      { name: "attachment_label", required: false, description: "Label for the video attachment." },
      { name: "tagged_object", required: false, description: "Object to tag (User/Page)." },
    ],
    examples: [
      "UserOne as PageOne make_post_video PostOne with {place: GroupOne, text: 'My post', attachment_label: VideoOne}",
      "UserOne make_post_video PostOne with {place: UserOne, attachment_label: VideoOne}",
    ],
  },
  {
    name: "make_comment",
    description:
      "Make a comment on an object. Mention and reply supported. Voice switcher supported.",
    signature:
      "Subject as Subject make_comment Label with {place, ?text, ?tagged_object, ?replied_comment}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the comment." }],
    keywordParams: [
      {
        name: "place",
        required: true,
        description: "Object to comment on (post/comment/photo/album).",
      },
      { name: "text", required: false, description: "Comment text. Default is random." },
      { name: "tagged_object", required: false, description: "Object to tag (User/Page)." },
      { name: "replied_comment", required: false, description: "Comment to reply to." },
    ],
    examples: [
      "UserTwo make_comment CommentLabel with {place: PostLabel, text: 'UserTwo is commenting here', tagged_object: UserOne}",
      "UserOne make_comment RepliedCommentLabel with {place: PostLabel, replied_comment: CommentLabel, text: 'That sounds great!'}",
      "UserTwo as PageOne make_comment CommentLabel with {place: AlbumOne}",
    ],
  },
  {
    name: "block",
    description: "Block another user. Voice switcher supported.",
    signature: "Subject as Subject block Label",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "User to block." }],
    keywordParams: [],
    examples: ["UserOne as PageOne block UserTwo", "UserOne block UserTwo"],
  },
  {
    name: "remove_role",
    description: "Remove any permission a user/page has from a place. Voice switcher supported.",
    signature: "Subject as Subject remove_role Label with {old_role}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Place to remove from." }],
    keywordParams: [{ name: "old_role", required: true, description: "User/Page to remove." }],
    examples: [
      "UserTwo remove_role EventOne with {old_role: PageOne}",
      "UserTwo as PageOne remove_role GroupOne with {old_role: UserOne}",
    ],
  },
  {
    name: "make_post_poll",
    description: "Post a poll. Voice switcher supported.",
    signature:
      "Subject as Subject make_post_poll Label with {place, type, ?anyone_add_options, ?choose_multiple_options, ?tagged_object}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the poll post." }],
    keywordParams: [
      { name: "place", required: true, description: "Where to post (User/Page/Event/Group)." },
      { name: "type", required: true, description: "Poll type.", values: ["text", "photo"] },
      {
        name: "anyone_add_options",
        required: false,
        description: "Allow participants to add options.",
        values: ["true", "false"],
      },
      {
        name: "choose_multiple_options",
        required: false,
        description: "Allow multiple selections.",
        values: ["true", "false"],
      },
      { name: "attachment_label", required: false, description: "Label for poll attachment." },
      { name: "tagged_object", required: false, description: "Object to tag." },
    ],
    examples: [
      "UserOne as PageOne make_post_poll PollPost with {place: GroupOne, type: photo, attachment_label: PollOne}",
      "UserOne make_post_poll PollPost with {place: PageOne, type: text, anyone_add_options: false}",
    ],
  },
  {
    name: "make_post_violation",
    description: "Make a post with a certain violation.",
    signature: "Subject as Subject make_post_violation Label with {place, type, ?tagged_object}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the post." }],
    keywordParams: [
      { name: "place", required: true, description: "Where to post (User/Page/Group)." },
      { name: "type", required: true, description: "Violation type." },
      { name: "tagged_object", required: false, description: "Object to tag." },
    ],
    examples: [
      "UserOne make_post_violation PostTwo with {place: GroupOne, type: hate}",
      "UserOne as PageOne make_post_violation PostPage with {place: PageTwo, type: nudity}",
    ],
  },
  {
    name: "add_cover_photo",
    description: "Add a cover photo to a user/page/group/event. Voice switcher for pages.",
    signature: "Subject as Subject add_cover_photo Label with {place}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for cover photo." }],
    keywordParams: [{ name: "place", required: true, description: "Where to add cover photo." }],
    examples: [
      "UserOne add_cover_photo CoverPhoto with {place: UserOne}",
      "UserOne as PageOne add_cover_photo CoverPhoto with {place: PageOne}",
    ],
  },
  {
    name: "add_story",
    description: "Add a story to a user or page. Voice switcher supported.",
    signature: "Subject as Subject add_story Label",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the story." }],
    keywordParams: [],
    examples: ["UserTwo add_story StoryOne", "UserTwo as PageTwo add_story StoryOne"],
  },
  {
    name: "change_post_audience",
    description: "Change the audience of a post.",
    signature: "Subject change_post_audience Label with {audience, ?friends}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Post to change." }],
    keywordParams: [
      {
        name: "audience",
        required: true,
        description: "New audience.",
        values: ["public", "friends", "only_me", "specific_friends", "friends_except"],
      },
      {
        name: "friends",
        required: false,
        description: "Specific friends to include/exclude.",
        isList: true,
      },
    ],
    examples: [
      "UserOne change_post_audience PostOne with {audience: public}",
      "UserOne change_post_audience PostOne with {audience: specific_friends, friends: [UserTwo, UserThree]}",
    ],
  },
  {
    name: "deactivate_account",
    description: "User deactivates its own account.",
    signature: "Subject deactivate_account Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Same user as actor." }],
    keywordParams: [],
    examples: ["UserTwo deactivate_account UserTwo"],
  },
  {
    name: "lock_profile",
    description: "User locks its own profile.",
    signature: "Subject lock_profile Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Same user as actor." }],
    keywordParams: [],
    examples: ["UserTwo lock_profile UserTwo"],
  },
  {
    name: "friend_user",
    description: "Send friend request (auto-accepted).",
    signature: "Subject2 friend_user Subject1",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "target", required: true, description: "User to befriend." }],
    keywordParams: [],
    examples: ["UserTwo friend_user UserOne"],
  },
  {
    name: "friend_request",
    description: "Send friend request (not auto-accepted).",
    signature: "Subject2 friend_request Subject1",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "target", required: true, description: "User to request." }],
    keywordParams: [],
    examples: ["UserTwo friend_request UserOne"],
  },
  {
    name: "like_post",
    description: "User likes a post.",
    signature: "Subject like_post Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Post to like." }],
    keywordParams: [],
    examples: ["UserTwo like_post PostOne"],
  },
  {
    name: "gen_token",
    description: "Generate an access token for Graph API usage.",
    signature: "Subject gen_token Label with {app, ?scopes}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for the token." }],
    keywordParams: [
      {
        name: "app",
        required: true,
        description: "App label or first-party app (fb4a|fbios|fbwww|ig|bm|pct).",
      },
      { name: "scopes", required: false, description: "List of permissions.", isList: true },
    ],
    examples: [
      "UserOne gen_token TokenOne with {app: fb4a}",
      "UserOne gen_token TokenOne with {app: AppOne, scopes: [ads_management, ads_read]}",
    ],
  },
  {
    name: "create_collection",
    description: "Create a saved collection.",
    signature: "Subject create_collection Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Label for collection." }],
    keywordParams: [],
    examples: ["UserTwo create_collection ColOne"],
  },
  {
    name: "add_collection_contributors",
    description: "Add contributors to a collection.",
    signature: "Subject add_collection_contributors Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Collection label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users/Pages to add.", isList: true },
    ],
    examples: ["UserOne add_collection_contributors CollectionOne with {new_roles: [UserTwo]}"],
  },
  {
    name: "save_to_collection",
    description: "Add posts to a collection.",
    signature: "Subject save_to_collection Label with {new_posts}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Collection label." }],
    keywordParams: [
      { name: "new_posts", required: true, description: "Posts to add.", isList: true },
    ],
    examples: ["UserOne save_to_collection ColOne with {new_posts: [PostOne, PostTwo, PostThree]}"],
  },
  {
    name: "like_page",
    description: "User likes a page.",
    signature: "Subject like_page Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Page to like." }],
    keywordParams: [],
    examples: ["UserTwo like_page PageTwo"],
  },
  {
    name: "going_event",
    description: "User marks 'going' on an event.",
    signature: "Subject going_event Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Event to attend." }],
    keywordParams: [],
    examples: ["UserTwo going_event EventOne"],
  },
  {
    name: "send_message",
    description: "Send a message to another user/page/chat group. Voice switcher supported.",
    signature: "Subject send_message Label with {text}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Recipient label." }],
    keywordParams: [{ name: "text", required: true, description: "Message text." }],
    examples: [
      "UserOne send_message UserTwo with {text: 'Test message'}",
      "UserTwo as PageTwo send_message UserOne with {text:Hey}",
    ],
  },
  {
    name: "share_post",
    description: "Share a post. Voice switcher supported.",
    signature: "Subject1 as Subject2 share_post label with {post, place, ?text}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Label for shared post." }],
    keywordParams: [
      { name: "post", required: true, description: "Post to share." },
      { name: "place", required: true, description: "Where to share." },
      { name: "text", required: false, description: "Text for the share." },
    ],
    examples: [
      "UserOne share_post SharedPost with {post: Post1, place: UserTwo}",
      "UserOne as PageOne share_post SharedPost with {post: Post1, place: EventOne}",
    ],
  },
  {
    name: "create_chat_group",
    description: "Create a chat group with other users.",
    signature: "Subject create_chat_group Label with {members, ?text}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Chat group label." }],
    keywordParams: [
      { name: "members", required: true, description: "List of friends.", isList: true },
      { name: "text", required: false, description: "Initial message text." },
    ],
    examples: [
      "UserOne create_chat_group ChatOne with {text: 'Welcome!', members:[UserTwo, UserThree]}",
    ],
  },
  {
    name: "follow",
    description: "Follow a user or page.",
    signature: "Subject follow Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User/Page to follow." }],
    keywordParams: [],
    examples: ["UserOne follow UserTwo", "UserOne follow PageOne"],
  },
  {
    name: "unfollow",
    description: "Unfollow a user or page.",
    signature: "Subject unfollow Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User/Page to unfollow." }],
    keywordParams: [],
    examples: ["UserOne unfollow UserTwo", "UserOne unfollow PageOne"],
  },
  {
    name: "create_additional_profile",
    description: "Create an additional profile for a user.",
    signature: "Subject create_additional_profile Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Profile label." }],
    keywordParams: [],
    examples: ["UserOne create_additional_profile ProfileOne"],
  },
  {
    name: "enable_professional_mode",
    description: "Enable professional mode for a user.",
    signature: "Subject enable_professional_mode Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User label." }],
    keywordParams: [],
    examples: ["UserOne enable_professional_mode UserOne"],
  },
  {
    name: "create_messenger_kids_account",
    description: "Create a messenger kids account (non-EU only).",
    signature: "Subject create_messenger_kids_account Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Account label." }],
    keywordParams: [],
    examples: ["UserOne create_messenger_kids_account MessengerKidsAccountOne"],
  },
  {
    name: "add_guardians",
    description: "Add guardians to a messenger kids account (non-EU only).",
    signature: "Subject add_guardians Label with {guardians}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Account label." }],
    keywordParams: [
      {
        name: "guardians",
        required: true,
        description: "Users to add as guardians.",
        isList: true,
      },
    ],
    examples: [
      "UserOne add_guardians MessengerKidsAccountOne with {guardians: [UserTwo, UserThree]}",
    ],
  },
  {
    name: "create_album",
    description: "Create an album. Voice switcher supported.",
    signature: "Subject as Subject create_album Label with {type, place}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Album label." }],
    keywordParams: [
      {
        name: "type",
        required: true,
        description: "Album type.",
        values: ["user", "shared", "page", "group"],
      },
      { name: "place", required: true, description: "Associated label for the type." },
    ],
    examples: [
      "UserOne create_album AlbumOne with {type: group, place: GroupOne}",
      "UserOne as PageOne create_album AlbumOne with {type: group, place: GroupOne}",
    ],
  },
  {
    name: "add_photo",
    description: "Add a photo to an album. Voice switcher supported.",
    signature: "Subject as Subject add_photo Label with {album, place}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Photo label." }],
    keywordParams: [
      { name: "album", required: true, description: "Album to add to." },
      { name: "place", required: true, description: "Where the album is." },
    ],
    examples: [
      "UserOne add_photo PhotoOne with {album: AlbumOne, place: GroupOne}",
      "UserOne as PageOne add_photo PhotoOne with {album: AlbumOne, place: GroupOne}",
    ],
  },
  {
    name: "add_video",
    description: "Add a video to an album. Voice switcher supported.",
    signature: "Subject as Subject add_video Label with {album, place}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Video label." }],
    keywordParams: [
      { name: "album", required: true, description: "Album to add to." },
      { name: "place", required: true, description: "Where the album is." },
    ],
    examples: [
      "UserOne add_video VideoOne with {album: AlbumOne, place: PageOne}",
      "UserOne as PageOne add_video VideoOne with {album: AlbumOne, place: GroupOne}",
    ],
  },
  {
    name: "tag_photo",
    description: "Tag a user or page on a photo. Voice switcher supported.",
    signature: "Subject tag_photo Label with {taggee}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Photo label." }],
    keywordParams: [{ name: "taggee", required: true, description: "User/Page to tag." }],
    examples: [
      "UserOne tag_photo PhotoOne with {taggee: UserTwo}",
      "UserOne as PageOne tag_photo PhotoOne with {taggee: PageTwo}",
    ],
  },
  {
    name: "add_contributors",
    description: "Add contributors to a shared album.",
    signature: "Subject add_contributors Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Album label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_contributors AlbumOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "create_page",
    description: "User creates a page.",
    signature: "Subject create_page Label with {?is_parent_location}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      {
        name: "is_parent_location",
        required: false,
        description: "Mark as parent location.",
        values: ["false", "true"],
      },
    ],
    examples: [
      "UserTwo create_page PageOne",
      "UserTwo create_page PageOne with {is_parent_location: true}",
    ],
  },
  {
    name: "add_business_location",
    description: "Add a business location sub-page to a parent location page.",
    signature: "Subject add_business_location Label with {page}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Location label." }],
    keywordParams: [{ name: "page", required: true, description: "Parent business page." }],
    examples: ["UserOne add_business_location LocOne with {page: PageOne}"],
  },
  {
    name: "add_page_facebook_access",
    description: "Give someone Facebook access to a Page.",
    signature: "Subject add_page_facebook_access Label with {new_roles, ?full}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to give access.", isList: true },
      {
        name: "full",
        required: false,
        description: "Full control (change roles, delete page).",
        values: ["true", "false"],
      },
    ],
    examples: ["UserOne add_page_facebook_access PageOne with {full: true, new_roles: [UserTwo]}"],
  },
  {
    name: "add_page_task_access",
    description: "Give someone task access to a Page.",
    signature: "Subject add_page_task_access Label with {new_role, tasks}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      { name: "new_role", required: true, description: "User to give access." },
      {
        name: "tasks",
        required: true,
        description: "List of tasks.",
        values: ["content", "messages", "community", "ads", "insights"],
        isList: true,
      },
    ],
    examples: [
      "UserOne add_page_task_access PageOne with {new_role: UserTwo, tasks: [content, messages, community, ads, insights]}",
    ],
  },
  {
    name: "unpublish_page",
    description: "Unpublish a page.",
    signature: "Subject unpublish_page Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page to unpublish." }],
    keywordParams: [],
    examples: ["UserTwo unpublish_page PageOne"],
  },
  {
    name: "publish_page",
    description: "Publish a page.",
    signature: "Subject publish_page Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page to publish." }],
    keywordParams: [],
    examples: ["UserTwo publish_page PageOne"],
  },
  {
    name: "set_age_restriction",
    description: "Set page age restriction.",
    signature: "Subject set_age_restriction Label with {age}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      {
        name: "age",
        required: true,
        description: "Age restriction.",
        values: ["0", "17", "18", "19", "21"],
      },
    ],
    examples: ["UserTwo set_age_restriction PageOne with {age: 21}"],
  },
  {
    name: "create_linked_group",
    description: "Create a Group linked to a Page.",
    signature: "Subject create_linked_group Label with {?page, ?privacy, ?members}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "page", required: false, description: "Page to be admin of group." },
      {
        name: "privacy",
        required: false,
        description: "Privacy setting.",
        values: ["private", "public"],
      },
      {
        name: "visibility",
        required: false,
        description: "Visibility.",
        values: ["anyone", "members_only"],
      },
      { name: "members", required: false, description: "Users to add.", isList: true },
    ],
    examples: [
      "UserOne create_linked_group GroupOne with {page: PageOne, members:[UserOne, UserFour]}",
    ],
  },
  {
    name: "add_group_admins",
    description: "Add admins to a Group. Voice switcher supported.",
    signature: "Subject as Subject add_group_admins Label with {new_roles, ?accept_invite}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add as admins.", isList: true },
      {
        name: "accept_invite",
        required: false,
        description: "Auto-accept invite.",
        values: ["true", "false"],
      },
    ],
    examples: [
      "UserTwo add_group_admins GroupOne with {new_roles: [UserOne, UserFour]}",
      "UserTwo as PageTwo add_group_admins GroupOne with {new_roles: [UserOne, UserFour]}",
    ],
  },
  {
    name: "add_group_moderators",
    description: "Add moderators to a Group. Voice switcher supported.",
    signature: "Subject as Subject add_group_moderators Label with {new_roles, ?accept_invite}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      {
        name: "new_roles",
        required: true,
        description: "Users to add as moderators.",
        isList: true,
      },
      {
        name: "accept_invite",
        required: false,
        description: "Auto-accept.",
        values: ["true", "false"],
      },
    ],
    examples: [
      "UserTwo add_group_moderators GroupOne with {new_roles: [UserOne, UserFour], accept_invite: false}",
    ],
  },
  {
    name: "add_group_members",
    description: "Add members to a Group. Voice switcher supported.",
    signature: "Subject as Subject add_group_members Label with {new_roles, ?accept_invite}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
      {
        name: "accept_invite",
        required: false,
        description: "Auto-accept.",
        values: ["true", "false"],
      },
    ],
    examples: ["UserTwo add_group_members GroupOne with {new_roles: [UserOne, UserFour]}"],
  },
  {
    name: "remove_member",
    description: "Remove user/page from group. Voice switcher supported.",
    signature: "Subject as Subject remove_member Label with {member}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "member", required: true, description: "User/Page to remove." },
      {
        name: "block",
        required: false,
        description: "Also block the user.",
        values: ["true", "false"],
      },
    ],
    examples: [
      "UserTwo remove_member GroupOne with {member: UserOne}",
      "UserTwo as PageOne remove_member GroupOne with {member: UserOne}",
    ],
  },
  {
    name: "create_group",
    description: "Create a group.",
    signature: "Subject create_group Label with {privacy}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "privacy", required: false, description: "Privacy.", values: ["public", "private"] },
      {
        name: "visibility",
        required: false,
        description: "Visibility.",
        values: ["anyone", "members_only"],
      },
    ],
    examples: ["UserTwo create_group GroupOne with {privacy: private, visibility: members_only}"],
  },
  {
    name: "create_event",
    description: "Create a past or future event.",
    signature:
      "Subject create_event Label with {place, ?privacy, ?is_past, ?post_permission, ?post_approval}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Event label." }],
    keywordParams: [
      { name: "place", required: true, description: "Where the event is hosted." },
      { name: "privacy", required: false, description: "Privacy.", values: ["public", "private"] },
      { name: "is_past", required: false, description: "Past event.", values: ["false", "true"] },
      {
        name: "post_permission",
        required: false,
        description: "Post permission.",
        values: ["admin", "anyone"],
      },
      { name: "post_approval", required: false, description: "Approval.", values: ["on", "off"] },
    ],
    examples: [
      "UserOne create_event EventOne with {place: PageOne, privacy: private, is_past: true}",
    ],
  },
  {
    name: "add_event_cohosts",
    description: "Add cohosts to an event.",
    signature: "Subject add_event_cohosts Label with {new_roles, ?accept_invite}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Event label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users/Pages to add.", isList: true },
      {
        name: "accept_invite",
        required: false,
        description: "Auto-accept.",
        values: ["true", "false"],
      },
    ],
    examples: ["UserOne add_event_cohosts EventOne with {new_roles: [UserTwo, PageOne]}"],
  },
  {
    name: "event_invite",
    description: "Invite users/pages to an event.",
    signature: "Subject event_invite Label with {invitees}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Event label." }],
    keywordParams: [
      { name: "invitees", required: true, description: "Users/Pages to invite.", isList: true },
    ],
    examples: ["UserOne event_invite EventOne with {invitees: [UserTwo, PageOne]}"],
  },
  {
    name: "cancel_event",
    description: "Cancel an event.",
    signature: "Subject cancel_event Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Event to cancel." }],
    keywordParams: [],
    examples: ["UserOne cancel_event EventOne"],
  },
  {
    name: "create_business",
    description: "Create a business.",
    signature: "Subject create_business Label with {?primary_page}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [
      { name: "primary_page", required: false, description: "Primary page for the business." },
    ],
    examples: ["UserOne create_business BusinessOne with {primary_page: PageOne}"],
  },
  {
    name: "add_biz_employees",
    description: "Add employees to a business.",
    signature: "Subject add_biz_employees Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_biz_employees BusinessOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_biz_admins",
    description: "Add admins to a business.",
    signature: "Subject add_biz_admins Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_biz_admins BusinessOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "create_ad_account",
    description: "Create an ad account.",
    signature: "Subject create_ad_account Label with {?business}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Ad account label." }],
    keywordParams: [
      { name: "business", required: false, description: "Business label (personal if omitted)." },
    ],
    examples: [
      "UserOne create_ad_account AdOne",
      "UserOne create_ad_account AdOne with {business: BizOne}",
    ],
  },
  {
    name: "add_ad_admins",
    description: "Add admins to ad account.",
    signature: "Subject add_ad_admins Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Ad account label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_ad_admins AdOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_ad_advertisers",
    description: "Add advertisers to ad account.",
    signature: "Subject add_ad_advertisers Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Ad account label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_ad_advertisers AdOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_ad_analysts",
    description: "Add analysts to ad account.",
    signature: "Subject add_ad_analysts Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Ad account label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_ad_analysts AdOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_biz_pages",
    description: "Add pages to a business.",
    signature: "Subject add_biz_pages Label with {pages}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [{ name: "pages", required: true, description: "Pages to add.", isList: true }],
    examples: ["UserOne add_biz_pages BusinessOne with {pages: [PageTwo, PageThree]}"],
  },
  {
    name: "biz_assign_page_role",
    description: "Assign business employee to page with role.",
    signature: "Subject biz_assign_page_role Label with {business, role, page}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User to assign." }],
    keywordParams: [
      { name: "business", required: true, description: "Business label." },
      {
        name: "role",
        required: true,
        description: "Role to assign.",
        values: ["admin", "editor", "moderator", "advertiser", "analyst"],
      },
      { name: "page", required: true, description: "Page label." },
    ],
    examples: [
      "UserOne biz_assign_page_role UserOne with {business: BizOne, role: moderator, page: PageOne}",
    ],
  },
  {
    name: "biz_assign_partner_asset",
    description: "Assign asset to a business partner.",
    signature: "Subject biz_assign_partner_asset Label with {partner, asset, type}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Initiating business." }],
    keywordParams: [
      { name: "partner", required: true, description: "Partner business." },
      { name: "asset", required: true, description: "Asset label." },
      {
        name: "type",
        required: true,
        description: "Asset type.",
        values: ["app", "page", "ad_account"],
      },
    ],
    examples: [
      "UserOne biz_assign_partner_asset BizOne with {partner: BizTwo, asset: PageOne, type: page}",
    ],
  },
  {
    name: "biz_link_app",
    description: "Link an app to a business.",
    signature: "Subject biz_link_app Label with {app}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [{ name: "app", required: true, description: "App to link." }],
    examples: ["UserOne biz_link_app BizOne with {app: AppOne}"],
  },
  {
    name: "biz_request_page_access",
    description: "Request page access on behalf of a business.",
    signature: "Subject biz_request_page_access Label with {page, ?permissions}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Business label." }],
    keywordParams: [
      { name: "page", required: true, description: "Page to access." },
      {
        name: "permissions",
        required: false,
        description: "Permission list.",
        values: ["manage", "create_content", "moderate", "advertise", "analyze", "manage_jobs"],
        isList: true,
      },
    ],
    examples: [
      "UserOne biz_request_page_access BizOne with {page:PageTwo, permissions: [manage, advertise]}",
    ],
  },
  {
    name: "create_shop",
    description: "Create a Shop with empty catalog.",
    signature: "Subject create_shop Label with {page, business}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Shop label." }],
    keywordParams: [
      { name: "page", required: true, description: "Page (primary page of business)." },
      { name: "business", required: true, description: "Business label." },
    ],
    examples: ["UserOne create_shop ShopOne with {page: PageOne, business: BusinessOne}"],
  },
  {
    name: "create_shop_item",
    description: "Create a Shop Item.",
    signature: "Subject create_shop_item Label with {shop, ?approved}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Item label." }],
    keywordParams: [
      { name: "shop", required: true, description: "Shop label." },
      {
        name: "approved",
        required: false,
        description: "Auto-approve.",
        values: ["false", "true"],
      },
    ],
    examples: ["UserOne create_shop_item ItemOne with {shop: ShopOne, approved: false}"],
  },
  {
    name: "create_pixel",
    description: "Create a pixel for a Business.",
    signature: "Subject create_pixel Label with {business}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Pixel label." }],
    keywordParams: [{ name: "business", required: true, description: "Business label." }],
    examples: ["UserOne create_pixel PixOne with {business: BizOne}"],
  },
  {
    name: "add_app_admins",
    description: "Add admins to an app.",
    signature: "Subject add_app_admins Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "App label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_app_admins AppOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_app_developers",
    description: "Add developers to an app.",
    signature: "Subject add_app_developers Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "App label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_app_developers AppOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_app_testers",
    description: "Add testers to an app.",
    signature: "Subject add_app_testers Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "App label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_app_testers AppOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "add_app_analytics_users",
    description: "Add analytics users to an app.",
    signature: "Subject add_app_analytics_users Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "App label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserOne add_app_analytics_users AppOne with {new_roles: [UserTwo, UserThree]}"],
  },
  {
    name: "create_learning_unit",
    description: "Create a learning unit in group. Voice switcher supported.",
    signature: "Subject as Subject create_learning_unit Label with {group}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Unit label." }],
    keywordParams: [{ name: "group", required: true, description: "Group to create in." }],
    examples: [
      "UserTwo create_learning_unit UnitOne with {group:GroupOne}",
      "UserTwo as PageOne create_learning_unit UnitOne with {group:GroupOne}",
    ],
  },
  {
    name: "create_doc",
    description: "Create a document in group. Voice switcher supported.",
    signature: "Subject as Subject create_doc Label with {group, ?can_edit}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Doc label." }],
    keywordParams: [
      { name: "group", required: true, description: "Group to create in." },
      {
        name: "can_edit",
        required: false,
        description: "Members can edit.",
        values: ["true", "false"],
      },
    ],
    examples: [
      "UserOne create_doc DocOne with {group: GroupOne}",
      "UserOne as PageOne create_doc DocOne with {group: GroupOne, can_edit: false}",
    ],
  },
  {
    name: "create_quiz",
    description: "Create a quiz in group.",
    signature: "Subject create_quiz Label with {group, unit}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Quiz label." }],
    keywordParams: [
      { name: "group", required: true, description: "Group for the quiz." },
      { name: "unit", required: true, description: "Learning unit for the quiz." },
    ],
    examples: ["UserOne create_quiz QuizOne with {group: GroupOne, unit: UnitOne}"],
  },
  {
    name: "mute_member",
    description: "Mute a member in group. Voice switcher supported.",
    signature: "Subject as Subject mute_member Label with {member}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [{ name: "member", required: true, description: "User to mute." }],
    examples: [
      "UserTwo mute_member GroupOne with {member: UserOne}",
      "UserTwo as PageOne mute_member GroupOne with {member: UserOne}",
    ],
  },
  {
    name: "pause_group",
    description: "Pause a group to prevent new content.",
    signature: "Subject pause_group Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group to pause." }],
    keywordParams: [],
    examples: ["UserOne pause_group GroupOne"],
  },
  {
    name: "unpause_group",
    description: "Unpause a group.",
    signature: "Subject unpause_group Label",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group to unpause." }],
    keywordParams: [],
    examples: ["UserOne unpause_group GroupOne"],
  },
  {
    name: "set_post_permission",
    description: "Set group posting permission. Voice switcher supported.",
    signature: "Subject as Subject set_post_permission Label with {value}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "value", required: true, description: "Permission.", values: ["anyone", "admin"] },
    ],
    examples: [
      "UserTwo set_post_permission GroupTwo with {value: anyone}",
      "UserTwo as PageOne set_post_permission GroupTwo with {value: admin}",
    ],
  },
  {
    name: "set_admin_approval",
    description: "Set group admin approval. Voice switcher supported.",
    signature: "Subject as Subject set_admin_approval Label with {value}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "value", required: true, description: "Approval setting.", values: ["on", "off"] },
    ],
    examples: [
      "UserTwo set_admin_approval GroupTwo with {value: on}",
      "UserTwo as PageOne set_admin_approval GroupTwo with {value: on}",
    ],
  },
  {
    name: "group_link_page",
    description: "Link group to a page.",
    signature: "Subject group_link_page Label with {page}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [{ name: "page", required: true, description: "Page to link." }],
    examples: ["UserTwo group_link_page GroupTwo with {page: PageOne}"],
  },
  {
    name: "group_unlink_page",
    description: "Unlink group from a page.",
    signature: "Subject group_unlink_page Label with {page}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [{ name: "page", required: true, description: "Page to unlink." }],
    examples: ["UserTwo group_unlink_page GroupTwo with {page: PageOne}"],
  },
  {
    name: "group_invite_friends",
    description: "Invite friends to a group.",
    signature: "Subject group_invite_friends Label with {invitees}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Group label." }],
    keywordParams: [
      { name: "invitees", required: true, description: "Friends to invite.", isList: true },
    ],
    examples: ["UserTwo group_invite_friends GroupOne with {invitees:[UserOne, UserThree]}"],
  },
  {
    name: "banhammer_user",
    description: "Ban user with enforcement type (ale, political, preharm).",
    signature: "Subject banhammer_user Label with {type}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User to ban." }],
    keywordParams: [
      {
        name: "type",
        required: true,
        description: "Ban type.",
        values: ["ale", "political", "preharm"],
      },
    ],
    examples: ["UserTwo banhammer_user UserTwo with {type: political}"],
  },
  {
    name: "add_checkpoint",
    description: "Enroll user into a checkpoint.",
    signature: "Subject add_checkpoint Label with {checkpoint}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User label." }],
    keywordParams: [
      {
        name: "checkpoint",
        required: true,
        description: "Checkpoint name.",
        values: ["Epsilon", "UFAC"],
      },
    ],
    examples: ["UserTwo add_checkpoint UserTwo with {checkpoint: Epsilon}"],
  },
  {
    name: "set_privacy_jurisdiction",
    description: "Set privacy jurisdiction (country) for a user.",
    signature: "Subject set_privacy_jurisdiction Label with {jurisdiction}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "User label." }],
    keywordParams: [
      { name: "jurisdiction", required: true, description: "Country code (EU, BR, US, IN, etc)." },
    ],
    examples: ["UserOne set_privacy_jurisdiction UserOne with {jurisdiction: IN}"],
  },
  {
    name: "create_ar_permission_group",
    description: "Create a Spark AR Hub permission group for a page.",
    signature: "Subject create_ar_permission_group Label with {page, users}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Permission group label." }],
    keywordParams: [
      { name: "page", required: true, description: "Page for the permission group." },
      { name: "users", required: true, description: "Users to add.", isList: true },
    ],
    examples: [
      "UserOne create_ar_permission_group ARPermGroupOne with {page: PageOne, users: [UserTwo, UserFour]}",
    ],
  },
  {
    name: "add_page_community_managers",
    description: "Add community managers to a Page.",
    signature: "Subject add_page_community_managers Label with {new_roles}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      { name: "new_roles", required: true, description: "Users to add.", isList: true },
    ],
    examples: ["UserTwo add_page_community_managers PageOne with {new_roles: [UserOne, UserFour]}"],
  },
  {
    name: "page_link_group",
    description: "Link a page to a group.",
    signature: "Subject page_link_group Label with {group}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [{ name: "group", required: true, description: "Group to link." }],
    examples: ["UserOne page_link_group PageOne with {group: GroupOne}"],
  },
  {
    name: "page_invite_friend",
    description: "Invite friends to like a page.",
    signature: "Subject page_invite_friend Label with {invitees}",
    supportsVoiceSwitcher: false,
    targetTypes: ["USER"],
    positionalParams: [{ name: "label", required: true, description: "Page label." }],
    keywordParams: [
      { name: "invitees", required: true, description: "Friends to invite.", isList: true },
    ],
    examples: ["UserOne page_invite_friend PageOne with {invitees: [FriendOne, FriendTwo]}"],
  },
  {
    name: "request_crossposting",
    description: "Request video crossposting between pages. Voice switcher supported.",
    signature: "Subject request_crossposting Label with {mode, ?accept_request}",
    supportsVoiceSwitcher: true,
    targetTypes: ["USER", "PAGE"],
    positionalParams: [{ name: "label", required: true, description: "Target page." }],
    keywordParams: [
      {
        name: "mode",
        required: true,
        description: "Crosspost mode.",
        values: ["automatic", "manual"],
      },
      {
        name: "accept_request",
        required: false,
        description: "Auto-accept.",
        values: ["true", "false"],
      },
    ],
    examples: [
      "UserOne as PageOne request_crossposting PageTwo with {mode: automatic, accept_request: true}",
    ],
  },
] as const;

// ── Lookup helpers ──────────────────────────────────────────────────────────

const setupIndex = new Map(SETUP_ENTITIES.map((e) => [e.type, e]));
const actionIndex = new Map(ACTIONS.map((a) => [a.name, a]));

export function getSetupEntity(type: string): SetupEntity | undefined {
  return setupIndex.get(type);
}

export function getAction(name: string): Action | undefined {
  return actionIndex.get(name);
}
